### ISSUE TITLE
"Failed to create //payload subcgroup: No such file or directory"

### ISSUE THREAD

**Issue by rffontenelle** [FFY00/build-arch-package#8]
This action's test is currently failing with `Failed to create //payload subcgroup: No such file or directory`. This happens when running build script in [run.sh](https://github.com/FFY00/build-arch-package/blob/b5ebd11c5dfe515aeafcad2c8e8f066b3017690c/run.sh#L31), and I believe to be related to running systemd-nspawn inside Docker (because extra-x86_64-build calls makechrootpkg, which calls arch-nspawn, which wraps systemd-spawn). See https://github.com/moby/moby/issues/44402

Steps to reproduce:
1. Enter Arch Linux docker container:
```shell
sudo systemctl start docker
sudo docker run -it --privileged --volume /sys/fs/cgroup:/sys/fs/cgroup archlinux
```
2. Inside the container, run the following commands:
```shell
pacman -Syu git
git clone https://github.com/FFY00/build-arch-package --depth=1
cd build-arch-package
export INPUT_PKGBUILD=.github/workflows/PKGBUILD INPUT_BUILD_SCRIPT=extra-x86_64-build INPUT_OUTDIR=$HOME/arch-packages GITHUB_SHA=1
./run.sh  # lots of output, ending with the error message
```
3. Running `extra-x86_64-build` again confirms where the output comes from.

**Comment by ljmf00** [comment]
@FFY00 do you know the root cause of this? This seem to be an update on the arch docker.

**Comment by duament** [comment]
I removed the bind mount of /sys/fs/cgroup and it just worked. Don't know why though.

**Comment by dougmassay** [comment]
> I removed the bind mount of /sys/fs/cgroup and it just worked. Don't know why though.

Confirmed. It just "works" without the bind mount.

**Comment by rffontenelle** [comment]
How did you do this? I tried but it didn't work: see the [commit](https://github.com/rffontenelle/build-arch-package/commit/191ebfff7884995fcc8b7396d8b4eaf17e0d8cdd) and the [workflow run](https://github.com/rffontenelle/build-arch-package/actions/runs/3832631222/jobs/6523169852)

**Comment by dougmassay** [comment]
Sorry. I don't think we're running the action's test yaml like you are. I was getting the same error reported when actually _using_ this action in my own project (the error was new). Removing the bind mount allowed the build of my project with this action to resume correctly.

```yaml
25h==> Retrieving sources...
==> WARNING: Skipping all source file integrity checks.
==> Extracting sources...
  -> Creating working copy of Sigil git repo...
Cloning into 'Sigil'...
done.
Switched to a new branch 'makepkg'
```


Have you tried updating to actions/checkout@v3? There's been some deprecation warnings about checkout@v2 for a while now.

**Comment by rffontenelle** [comment]
> Sorry. I don't think we're running the action's test yaml like you are.

Well, considering that we're trying to fix this project, and considering that the test reflects how we use it, then that's the way to go I believe. 😁

> Have you tried updating to actions/checkout@v3? There's been some deprecation warnings about checkout@v2 for a while now.

actions/checkout just git-clones the repository, so it doesn't affects how the build happens.

But, yeah, I tested when proposing #10

**Comment by dougmassay** [comment]
I can't be certain, but I think the problem is that you're testing your changes on a fork (rffontenelle/build-arch-package), but unless you've modified the PKGBUILD on that fork, it's going to be looking for a non-existent commit tree in the upstream repo (this one - FFY00/build-arch-package) since the repo in the PKGBUILD seems to be hard-coded to this one.

```bash
_commit=%COMMIT%
pkgver=dummy
pkgrel=1
pkgdesc='build-arch-package github action test package'
arch=('any')
url='https://github.com/FFY00/build-arch-package'
license=('custom:None')
makedepends=('git')
source=("git+$url.git#commit=$_commit")
```

**Comment by rffontenelle** [comment]
@dougmassay you are correct. I added this fix to my PR.

**Comment by dougmassay** [comment]
Sounds good.

To make it easier to fork, test, commit and ultimately submit a pull request, I'd recommend having placeholder text for the owner/repo portion of the url in the PKGBUILD, and then add a step to test.yml that replaces that placeholder (simple sed command) with $GITHUB_REPOSITORY right after the actions/checkout step and before building. That way the correct repo would always be used.

**Comment by rffontenelle** [comment]
@dougmassay The solution below works. Looks good or have a better/prettier idea?

```diff
diff --git a/.github/workflows/PKGBUILD b/.github/workflows/PKGBUILD
index 6e19496..948d5db 100644
--- a/.github/workflows/PKGBUILD
+++ b/.github/workflows/PKGBUILD
@@ -7,7 +7,7 @@ pkgver=dummy
 pkgrel=1
 pkgdesc='build-arch-package github action test package'
 arch=('any')
-url='https://github.com/FFY00/build-arch-package'
+url='%URL%'
 license=('custom:None')
 makedepends=('git')
 source=("git+$url.git#commit=$_commit")
diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
index 18f37d2..6643590 100644
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -9,6 +9,8 @@ jobs:
       options: --privileged
     steps:
       - uses: actions/checkout@v3
+      - name: Set proper repository name in PKGBUILD
+        run: sed -i "s|%URL%|${{ github.server_url }}/${{ github.repository }}|" .github/workflows/PKGBUILD
       - name: Build Arch Linux package
         uses: ./
```

In the workflow run logs, it will show the following:

![Captura de tela de 2023-01-09 14-29-58](https://user-images.githubusercontent.com/1571783/211370328-d78c039f-e004-43b5-9731-ceda0e16a77d.png)

**Comment by dougmassay** [comment]
Looks fine to me. Anything that allows someone to fork and run the test without having to first modify the test PKGBUILD makes sense to me.

**Comment by rffontenelle** [comment]
Awesome. PR updated with that patch. @FFY00 please consider review it when possible. Thanks!
